baseURL = ""
languageCode = "en-us"
title = "Giulia & Michele"
theme = "alpha-church"


rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "News"
    url = "/news"
    weight = 2
	
  [[menu.main]]
    name = "Cerimonia"
    url = "/church"
    weight = 3

  [[menu.main]]
    name = "Ricevimento"
    url = "/reception"
    weight = 4

  [[menu.main]]
    name = "Lista Nozze"
    url = "/wedding_list"
    weight = 5

# Paramaters for the whole site
[params]
  author = "Michele Ciocchetta"
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp

  instant_page = true

  customCSS = ["/css/my.css"]

  [params.banner]
    image = "img/banner.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

   
   
  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    #
    #If you use php, you need to host this site on a Server capable of running php. 
    # Please edit the /static/contact_mail.php file from the exampleSite.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""
	

    [params.footer]
      copyright = [
                   "by Michele Ciocchetta"
                  ]

    