baseURL = "giuliamichewedding.info"
languageCode = "en-us"
defaultContentLanguage = "it"
title = "Giulia & Michele"
theme = "alpha-church"

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-180319764-1"

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

  
[languages]
  [languages.it]
    weight = 1	
	[languages.it.menu]
	  [[languages.it.menu.main]]
		name = "Home"
		url = "/"
		weight = 1
	  [[languages.it.menu.main]]
		name = "Notizie"
		url = "/news"
		weight = 2		
	  [[languages.it.menu.main]]
		name = "Cerimonia"
		url = "/church"
		weight = 3
	  [[languages.it.menu.main]]
		name = "Lista Nozze"
		url = "/weddinglist"
		weight = 4	
	  [[languages.it.menu.main]]
		name = "Français"
		url = "/fr"
		weight = 5	
	[languages.it.params.contact]
		service = "netlify"
		confirm_page = "/contact_thanks"
  [languages.fr]
    weight = 2	
    [languages.fr.menu]
	  [[languages.fr.menu.main]]
		name = "Home"
		url = "/fr"
		weight = 1
	  [[languages.fr.menu.main]]
		name = "Nouvelles"
		url = "/fr/news"
		weight = 2		
	  [[languages.fr.menu.main]]
		name = "Célebration"
		url = "/fr/church"
		weight = 3
	  [[languages.fr.menu.main]]
		name = "Liste de mariage"
		url = "/fr/weddinglist"
		weight = 4
	  [[languages.fr.menu.main]]
		name = "Italiano"
		url = "/"
		weight = 5	
	[languages.fr.params.contact]
		service = "netlify"
		confirm_page = "/fr/contact_thanks"
		
#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.


# Paramaters for the whole site
[params]
  author = "Michele Ciocchetta"

  instant_page = true

  customCSS = ["/css/my.css"]

  [params.banner]
    image = "img/banner_original.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

   
   
  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    #
    #If you use php, you need to host this site on a Server capable of running php. 
    # Please edit the /static/contact_mail.php file from the exampleSite.
    #service = "netlify"
    # confirm_page = "/contact_thanks"
    # formspree_email=""
	

    [params.footer]
      copyright = [
                   "by Michele Ciocchetta",
				   "Artwork by [Erica Bonvicini](https://www.instagram.com/bonvicini.erica)"
                  ]

    